project:
  type: website

website:
  title: "Gerencia de Desarrollo Urbano y Rural"
  favicon: images/pdu.png  
  
  page-footer: 
    right: "[Quarto](https://quarto.org/) | [vetiver](https://github.com/rstudio/vetiver.rstudio.com)"
    left: "& CC - GDUR - MPA"
 
  navbar:
    logo: images/pdu.png
    href: https://openscapes.org
    right:
    - text: "Zonificación"                      
      href: zonificacion.qmd
    

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contenido
    toc-location: left
execute:
  freeze: auto